version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount the client app for live changes
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./contact-app-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./contact-app-server:/app         # Mount the server code for live changes
      - /app/node_modules
    environment:
      - NODE_ENV=production